export { default as authControllers } from './auth.controllers.js'
export { default as complementsControllers } from './complements.controllers.js'
export { default as usersControllers } from './users.controllers.js'
export { default as permissionsControllers } from './permissions.controllers.js'
export { default as profileControllers } from './profile.controllers.js'
export { default as categoriesControllers } from './categories.controllers.js'
