export { default as usersRoutes } from './users.routes.js'
export { default as authRoutes } from './auth.routes.js'
export { default as permissionsRoutes } from './permissions.routes.js'
export { default as profileRoutes } from './profile.routes.js'
export { default as complementsRoutes } from './complements.routes.js'
